#!/bin/bash

DIR_PATH=$1
DIR_NUM=$2
DIR_NAME=$3
FILE_NUM=$4
FILE_NAME=$5
FILE_SIZE=$6

source error_check.sh $DIR_PATH $DIR_NUM $DIR_NAME $FILE_NUM $FILE_NAME $FILE_SIZE

./create_files.sh $DIR_PATH $DIR_NUM $DIR_NAME $FILE_NUM $FILE_NAME $FILE_SIZE