{
 "title": "My dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[5m]))) * 100",
     "legendFormat": " Загрузка ЦП"
    }
   ]
  },
  {
   "title": "Count Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\", instance=\"localhost:9100\"}[5m])",
     "legendFormat": "Кол-во операций ввода/вывода на жестком диске"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}",
     "legendFormat": "Доступная память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}",
     "legendFormat": "Занятая память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}",
     "legendFormat": "Всего памяти"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Доступная оперативная память"
    }
   ]
  }
 ]
}